# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Детализация проекта',
                'verbose_name_plural': 'Детализация проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True)),
                ('desc', tinymce.models.HTMLField(verbose_name='описание')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project_images',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='landing_page.Projects', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='project_images',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
