# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField(max_length=50)),
                ('site_description', models.TextField(max_length=100)),
                ('contact_streetAddress', models.TextField(max_length=200)),
                ('contact_addressLocality', models.TextField(max_length=200)),
                ('contact_addressRegion', models.TextField(max_length=200)),
                ('contact_telephone', models.TextField(max_length=30)),
                ('contact_hours', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='project_images',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='уникальное название'),
        ),
    ]
