# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('landing_page', '0002_auto_20180216_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_addressLocality',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_addressRegion',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_hours',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_streetAddress',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
