# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20180220_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='desc',
            field=models.TextField(max_length=150),
        ),
    ]
